INSERT INTO COURT(ID,NAME, COURT_TYPE, RENOVATION_STATUS) VALUES ('3','testName1', 'INDOOR','UNDER_RENOVATION');
INSERT INTO COURT(ID,NAME,COURT_TYPE, RENOVATION_STATUS) VALUES ('4','testName2', 'OUTDOOR','RENOVATED');
INSERT INTO COURT(ID,NAME,COURT_TYPE, RENOVATION_STATUS) VALUES ('7','testName3', 'OUTDOOR','NOT_RENOVATED');